'use strict';

export default {
    'METADATA_CREATION_PENDING': 'METADATA_CREATION_PENDING',
    'METADATA_CREATION_FAILED': 'METADATA_CREATION_FAILED',
    'METADATA_CREATION_COMPLETED': 'COMPLETED'
};
