export const solrCaseFields = [
  "case_createdByName",
  "case_createdDate",
  "case_lastModifiedDate",
  "case_lastModifiedByName",
  "id",
  "uri",
  "case_summary",
  "case_status",
  "case_product",
  "case_version",
  "case_accountNumber",
  "case_number",
  "case_contactName",
  "case_owner",
  "case_severity",
  "case_last_public_update_date",
  "case_last_public_update_by"
]